# Generated by Django 5.1.4 on 2025-01-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='currency',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
