# Generated by Django 5.1.4 on 2025-01-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomesource',
            options={'verbose_name_plural': 'Sources'},
        ),
    ]
